import { useCallback, useEffect, useMemo, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { CheckCircle2, Pencil, Search, Users } from "lucide-react";
import DashboardLayout from "@/components/layout/DashboardLayout.jsx";
import { ConfirmDialog, Loader, Modal, StatusBadge, Toast } from "@/components/common/Ui.jsx";
import apiClient, { getApiErrorMessage } from "@/api/apiClient.js";
import { apiEndpoints } from "@/api/apiEndpoints.js";
import { useAcademicContext } from "@/context/AcademicContext.jsx";
import "./SectionAllocationPage.css";

const list = (value) => [value, value?.data, value?.Data, value?.items, value?.Items, value?.groups, value?.Groups, value?.programs, value?.Programs, value?.sections, value?.Sections, value?.students, value?.Students, value?.academicLevels, value?.AcademicLevels, value?.data?.items].find(Array.isArray) ?? [];
const body = (response) => response?.data?.data ?? response?.data?.Data ?? response?.data ?? {};
const get = (row, ...keys) => keys.map((key) => row?.[key]).find((value) => value != null);
const number = (value) => Number(value ?? 0);
const filled = (value) => value != null && String(value).trim() !== "" && String(value) !== "0";
const sectionId = (row) => get(row, "sectionId", "SectionId", "id", "Id");
const studentId = (row) => get(row, "studentId", "StudentId", "id", "Id");
const sectionValue = (row) => get(row, "sectionId", "SectionId", "existingSectionId", "ExistingSectionId", "allocatedSectionId", "AllocatedSectionId");
const sectionName = (row) => get(row, "sectionName", "SectionName", "existingSectionName", "ExistingSectionName", "allocatedSectionName", "AllocatedSectionName");
const capacity = (row) => get(row, "maximumStrength", "MaximumStrength", "totalCapacity", "TotalCapacity", "capacity", "Capacity");
const count = (row) => get(row, "allocatedCount", "AllocatedCount", "alreadyAllocated", "AlreadyAllocated", "currentAllocatedCount", "CurrentAllocatedCount");
const date = (value) => value ? new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)) : "—";
const matches = (row, context) => ["academicYearId", "academicLevelId", "groupId", "programId"].every((key) => String(get(row, key, key[0].toUpperCase() + key.slice(1)) ?? "") === String(context[key]));
const mapStudent = (admission = {}, record = {}) => ({ id: studentId(record), admissionNo: get(record, "admissionNo", "AdmissionNo") ?? get(admission, "admissionNo", "AdmissionNo") ?? "—", name: get(record, "studentName", "StudentName", "name", "Name") ?? [get(admission, "firstName", "FirstName"), get(admission, "lastName", "LastName")].filter(Boolean).join(" "), admissionDate: get(record, "admissionDate", "AdmissionDate") ?? get(admission, "admissionDate", "AdmissionDate"), academicYearId: get(record, "academicYearId", "AcademicYearId") ?? get(admission, "academicYearId", "AcademicYearId"), academicLevelId: get(record, "academicLevelId", "AcademicLevelId") ?? get(admission, "academicLevelId", "AcademicLevelId"), groupId: get(record, "groupId", "GroupId") ?? get(admission, "groupId", "GroupId"), programId: get(record, "programId", "ProgramId") ?? get(admission, "programId", "ProgramId"), sectionId: sectionValue(record) ?? sectionValue(admission), sectionName: sectionName(record) ?? sectionName(admission), rollNo: get(record, "rollNo", "RollNo", "rollNumber", "RollNumber") ?? get(admission, "rollNo", "RollNo") });

export default function SectionAllocationPage() {
  const { selectedBoardId, selectedAcademicYear, selectedAcademicYearId, academicYearsLoading } = useAcademicContext();
  const [filters, setFilters] = useState({ academicLevelId: "", groupId: "", programId: "", sectionId: "" });
  const [masters, setMasters] = useState({ levels: [], groups: [], programs: [], sections: [] });
  const [students, setStudents] = useState([]); const [sectionCounts, setSectionCounts] = useState({}); const [sectionStudents, setSectionStudents] = useState([]);
  const [loading, setLoading] = useState(true); const [studentLoading, setStudentLoading] = useState(false); const [busy, setBusy] = useState(""); const [confirming, setConfirming] = useState("");
  const [preview, setPreview] = useState(null); const [search, setSearch] = useState(""); const [editing, setEditing] = useState(null); const [refresh, setRefresh] = useState(0); const [toast, setToast] = useState({ message: "", type: "success" });
  const location = useLocation(); const navigate = useNavigate();
  const activeTab = location.pathname.endsWith("/allocated") ? "allocated" : location.pathname.endsWith("/roll-numbers") ? "roll" : "allocation";
  const hasSectionFilter = activeTab !== "allocation";
  const readyContext = Boolean(selectedBoardId && selectedAcademicYearId && filters.academicLevelId && filters.groupId && filters.programId);
  const readySection = readyContext && Boolean(filters.sectionId);
  const context = useMemo(() => ({ academicYearId: number(selectedAcademicYearId), academicLevelId: number(filters.academicLevelId), groupId: number(filters.groupId), programId: number(filters.programId) }), [selectedAcademicYearId, filters]);
  const say = useCallback((reason) => setToast({ message: typeof reason === "string" ? reason : getApiErrorMessage(reason), type: "error" }), []);
  const update = (key, value) => { setFilters((current) => ({ ...current, [key]: value, ...(key === "academicLevelId" ? { groupId: "", programId: "", sectionId: "" } : {}), ...(key === "groupId" ? { programId: "", sectionId: "" } : {}), ...(key === "programId" ? { sectionId: "" } : {}) })); if (["academicLevelId", "groupId", "programId"].includes(key)) setPreview(null); setStudents([]); setSectionStudents([]); setSearch(""); };

  useEffect(() => { setFilters({ academicLevelId: "", groupId: "", programId: "", sectionId: "" }); setPreview(null); if (!selectedBoardId) return undefined; let active = true; setLoading(true); apiClient.get(apiEndpoints.boards.academicLevels, { params: { boardId: selectedBoardId } }).then((response) => active && setMasters({ levels: list(body(response)), groups: [], programs: [], sections: [] })).catch(say).finally(() => active && setLoading(false)); return () => { active = false; }; }, [selectedBoardId, say]);
  useEffect(() => { setFilters({ academicLevelId: "", groupId: "", programId: "", sectionId: "" }); setPreview(null); setStudents([]); }, [selectedAcademicYearId]);
  useEffect(() => { if (!selectedBoardId || !selectedAcademicYearId || !filters.academicLevelId) return; apiClient.get(apiEndpoints.groups.getByBoard(selectedBoardId), { params: { academicYearId: selectedAcademicYearId, academicLevelId: filters.academicLevelId, isActive: true } }).then((response) => setMasters((current) => ({ ...current, groups: list(body(response)), programs: [], sections: [] }))).catch(say); }, [filters.academicLevelId, say, selectedAcademicYearId, selectedBoardId]);
  useEffect(() => { if (!filters.groupId) return; apiClient.get(apiEndpoints.groups.programs(filters.groupId)).then((response) => setMasters((current) => ({ ...current, programs: list(body(response)), sections: [] }))).catch(say); }, [filters.groupId, say]);
  useEffect(() => { if (!readyContext) return; apiClient.get(apiEndpoints.sections.list, { params: { boardId: number(selectedBoardId), ...context, ProgramId: context.programId, IsActive: true, pageSize: 1000 } }).then((response) => setMasters((current) => ({ ...current, sections: list(body(response)).filter((section) => matches(section, context)) }))).catch(say); }, [context, readyContext, refresh, say, selectedBoardId]);
  const loadStudents = useCallback(async () => { if (!readyContext) return; setStudentLoading(true); try { const [admissionsResponse, studentsResponse] = await Promise.all([apiClient.get(apiEndpoints.admissions.getAll), apiClient.get(apiEndpoints.students.getAll)]); const records = list(body(studentsResponse)); const byAdmission = new Map(records.map((item) => [String(get(item, "admissionNo", "AdmissionNo") ?? ""), item])); setStudents(list(body(admissionsResponse)).filter((item) => matches(item, context)).map((admission) => mapStudent(admission, byAdmission.get(String(get(admission, "admissionNo", "AdmissionNo") ?? "")) ?? {})).filter((student) => student.id != null && matches(student, context))); } catch (error) { say(error); } finally { setStudentLoading(false); } }, [context, readyContext, say]);
  useEffect(() => { loadStudents(); }, [loadStudents]);
  useEffect(() => { if (!readyContext || !masters.sections.length) return setSectionCounts({}); let active = true; Promise.allSettled(masters.sections.map(async (section) => ({ id: sectionId(section), rows: list(body(await apiClient.get(apiEndpoints.students.getBySection(sectionId(section))))) }))).then((results) => active && setSectionCounts(Object.fromEntries(results.filter((result) => result.status === "fulfilled").map((result) => [String(result.value.id), result.value.rows.length])))); return () => { active = false; }; }, [masters.sections, readyContext, refresh]);
  useEffect(() => { if (!readySection) return setSectionStudents([]); apiClient.get(apiEndpoints.students.getBySection(filters.sectionId)).then((response) => setSectionStudents(list(body(response)))).catch(say); }, [filters.sectionId, readySection, refresh, say]);

  const sections = useMemo(() => masters.sections.map((section) => { const id = sectionId(section); const maximum = number(capacity(section)); const allocated = sectionCounts[String(id)] ?? number(count(section)); return { ...section, id, maximum, allocated, available: Math.max(0, maximum - allocated) }; }), [masters.sections, sectionCounts]);
  const unallocated = students.filter((student) => !filled(student.sectionId)); const selectedSection = sections.find((section) => String(section.id) === String(filters.sectionId));
  const allocatedRows = useMemo(() => sectionStudents.map((record) => { const admissionNo = String(get(record, "admissionNo", "AdmissionNo") ?? ""); const contextStudent = students.find((student) => String(student.admissionNo) === admissionNo) ?? {}; return { ...mapStudent(contextStudent, record), sectionId: sectionValue(record) ?? filters.sectionId, sectionName: sectionName(record) ?? get(selectedSection, "sectionName", "SectionName") }; }), [filters.sectionId, sectionStudents, selectedSection, students]);
  const visibleAllocated = useMemo(() => { const query = search.trim().toLowerCase(); return query ? allocatedRows.filter((student) => `${student.name} ${student.admissionNo} ${student.rollNo}`.toLowerCase().includes(query)) : allocatedRows; }, [allocatedRows, search]);
  const previewRows = list(preview?.students); const totalAvailable = sections.reduce((sum, section) => sum + section.available, 0); const rollAssigned = allocatedRows.filter((student) => filled(student.rollNo)).length;
  const previewAllocation = async () => { if (!readyContext) return say("Select Academic Level, Group and Program first."); setBusy("section-preview"); try { setPreview(body(await apiClient.post(apiEndpoints.sectionRollAllocation.sectionPreview, context))); } catch (error) { say(error); } finally { setBusy(""); } };
  const confirmSections = async () => { setBusy("section-confirm"); try { const response = await apiClient.post(apiEndpoints.sectionRollAllocation.sectionConfirm, context); setToast({ message: get(body(response), "message", "Message") ?? "Section allocation completed successfully.", type: "success" }); setPreview(null); setConfirming(""); setRefresh((value) => value + 1); await loadStudents(); } catch (error) { say(error); } finally { setBusy(""); } };
  const previewRolls = async () => { if (!readySection) return say("Please select a Section."); setBusy("roll-preview"); try { await apiClient.post(apiEndpoints.sectionRollAllocation.rollPreview, context); setConfirming("roll"); } catch (error) { say(error); } finally { setBusy(""); } };
  const confirmRolls = async () => { setBusy("roll-confirm"); try { const response = await apiClient.post(apiEndpoints.sectionRollAllocation.rollConfirm, context); setToast({ message: get(body(response), "message", "Message") ?? "Roll number allocation completed successfully.", type: "success" }); setConfirming(""); setRefresh((value) => value + 1); await loadStudents(); } catch (error) { say(error); } finally { setBusy(""); } };
  const saveEdit = async () => { const destination = sections.find((section) => String(section.id) === String(editing?.nextSectionId)); if (destination && destination.available <= 0 && String(editing.sectionId) !== String(editing.nextSectionId)) return say("The selected section has reached its maximum strength."); setBusy("edit"); try { await apiClient.put(apiEndpoints.sectionRollAllocation.updateStudent(editing.id), { groupId: number(editing.groupId), programId: number(editing.programId), sectionId: number(editing.nextSectionId), ...(filled(editing.rollNo) ? { rollNo: editing.rollNo } : {}) }); setToast({ message: "Allocation updated successfully.", type: "success" }); setEditing(null); setRefresh((value) => value + 1); await loadStudents(); } catch (error) { say(error); } finally { setBusy(""); } };
  const selectOptions = (items, ids, labels) => items.map((item) => <option key={get(item, ...ids)} value={get(item, ...ids)}>{get(item, ...labels) ?? "Unnamed"}</option>);
  const tabPath = (tab) => tab === "allocated" ? "/dashboard/section-allocation/allocated" : tab === "roll" ? "/dashboard/section-allocation/roll-numbers" : "/dashboard/section-allocation";

  return <DashboardLayout title="Section Allocation" subtitle="Manage student section allocation and roll number assignment." breadcrumb={["People", "Section Allocation"]}><main className="allocation-page"><nav className="allocation-tabs" aria-label="Section allocation views">{[["allocation", "Section Allocation"], ["allocated", "Allocated Students"], ["roll", "Roll Numbers"]].map(([tab, label]) => <button key={tab} type="button" className={activeTab === tab ? "is-active" : ""} onClick={() => navigate(tabPath(tab))}>{label}</button>)}</nav><section className="cms-card allocation-workspace"><div className="cms-card-body"><div className={`allocation-filter-grid ${hasSectionFilter ? "has-section-filter" : ""}`}><div className="cms-field"><span>Academic Year</span><div className="allocation-year-value">{selectedAcademicYear?.name ?? selectedAcademicYear?.label ?? (academicYearsLoading ? "Loading academic year..." : "Select an Academic Year in the header")}</div></div><SelectField label="Academic Level" value={filters.academicLevelId} disabled={!selectedBoardId || !selectedAcademicYearId || loading} onChange={(value) => update("academicLevelId", value)}>{selectOptions(masters.levels, ["academicLevelId", "AcademicLevelId", "levelId", "LevelId"], ["academicLevelName", "AcademicLevelName", "levelName", "LevelName"])}</SelectField><SelectField label="Group" value={filters.groupId} disabled={!filters.academicLevelId} onChange={(value) => update("groupId", value)}>{selectOptions(masters.groups, ["groupId", "GroupId"], ["groupName", "GroupName"])}</SelectField><SelectField label="Program" value={filters.programId} disabled={!filters.groupId} onChange={(value) => update("programId", value)}>{selectOptions(masters.programs, ["programId", "ProgramId"], ["programName", "ProgramName"])}</SelectField>{hasSectionFilter ? <SelectField label="Section" value={filters.sectionId} disabled={!filters.programId} onChange={(value) => update("sectionId", value)}>{sections.map((section) => <option key={section.id} value={section.id}>{get(section, "sectionName", "SectionName")} ({section.allocated}/{section.maximum})</option>)}</SelectField> : null}</div></div>
    {activeTab === "allocation" ? <><CardHead title={`Students to Allocate (${unallocated.length})`} text="Students waiting for a section assignment." icon={<Users size={20} />} />{studentLoading ? <Loader label="Loading students to allocate..." /> : <StudentTable students={unallocated} pending />} {readyContext ? <div className="allocation-section-capacities"><div className="allocation-section-capacities-head"><div><h3>Available Target Sections</h3><p>Current capacity for sections mapped to this program.</p></div><button className="cms-btn cms-btn-primary" disabled={Boolean(busy) || !unallocated.length || !sections.length} onClick={previewAllocation}>{busy === "section-preview" ? "Preparing..." : "Preview Section Allocation"}</button></div>{sections.length ? <div className="allocation-capacity-grid">{sections.map((section) => <div className="allocation-capacity-item" key={section.id}><strong>{get(section, "sectionName", "SectionName")}</strong><span>{section.allocated} / {section.maximum}</span><small>{section.available} Available</small></div>)}</div> : <div className="cms-empty">No sections are configured for this program.</div>}</div> : null}{readyContext && !studentLoading && !unallocated.length ? <div className="allocation-empty-note">All admitted students for this program have been assigned to sections.</div> : null}{preview ? <PreviewCard preview={preview} sections={sections} program={get(masters.programs.find((program) => String(get(program, "programId", "ProgramId")) === String(filters.programId)), "programName", "ProgramName")} totalAvailable={totalAvailable} busy={busy} onCancel={() => setPreview(null)} onConfirm={() => setConfirming("section")} /> : null}</> : null}
    {activeTab === "allocated" ? <><CardHead title={`Allocated Students (${allocatedRows.length})`} text="Students assigned to the selected section." icon={<Users size={20} />} /><SearchBox value={search} onChange={setSearch} /><StudentTable students={visibleAllocated} onEdit={(student) => setEditing({ ...student, nextSectionId: student.sectionId })} iconOnlyEdit showAdmissionDate={false} /></> : null}
    {activeTab === "roll" ? <><CardHead title="Roll Numbers" text="Review roll numbers for the selected section." icon={<CheckCircle2 size={20} />} />{selectedSection ? <div className="allocation-summary allocation-roll-summary"><Summary label="Section" value={get(selectedSection, "sectionName", "SectionName")} /><Summary label="Total Students" value={allocatedRows.length} /><Summary label="Roll Numbers Assigned" value={rollAssigned} /><Summary label="Pending" value={Math.max(0, allocatedRows.length - rollAssigned)} /></div> : null}<SearchBox value={search} onChange={setSearch} /><StudentTable students={visibleAllocated} showAdmissionDate={false} showStatus={false} /><div className="allocation-selection-footer"><span>{Math.max(0, allocatedRows.length - rollAssigned)} roll number{Math.max(0, allocatedRows.length - rollAssigned) === 1 ? "" : "s"} pending</span><button className="cms-btn cms-btn-primary" disabled={!readySection || Boolean(busy) || !allocatedRows.length} onClick={previewRolls}>{busy === "roll-preview" ? "Preparing..." : "Generate Roll Numbers"}</button></div></> : null}
  </section></main>{confirming ? <ConfirmDialog title={confirming === "section" ? "Confirm Section Allocation" : "Confirm Roll Number Generation"} message={confirming === "section" ? "Confirm the previewed section allocation? This will save the proposed changes." : "Generate roll numbers using the existing allocation rules?"} confirmLabel={confirming === "section" ? "Confirm Section Allocation" : "Generate Roll Numbers"} loading={busy === `${confirming}-confirm`} loadingLabel="Saving..." onCancel={() => !busy && setConfirming("")} onConfirm={confirming === "section" ? confirmSections : confirmRolls} /> : null}{editing ? <Modal title="Edit Allocation" onClose={() => !busy && setEditing(null)} footer={<><button className="cms-btn cms-btn-ghost" onClick={() => setEditing(null)}>Cancel</button><button className="cms-btn cms-btn-primary" disabled={Boolean(busy) || !editing.nextSectionId} onClick={saveEdit}>{busy === "edit" ? "Saving..." : "Save Allocation"}</button></>}><div className="allocation-student-summary"><strong>{editing.name}</strong><span>Admission No: {editing.admissionNo}</span></div><SelectField label="New Section" value={editing.nextSectionId} onChange={(nextSectionId) => setEditing((current) => ({ ...current, nextSectionId }))}>{sections.map((section) => <option key={section.id} value={section.id} disabled={section.available <= 0 && String(section.id) !== String(editing.sectionId)}>{get(section, "sectionName", "SectionName")}</option>)}</SelectField></Modal> : null}<Toast message={toast.message} type={toast.type} onClose={() => setToast({ message: "", type: "success" })} /></DashboardLayout>;
}

function SelectField({ label, value, disabled, onChange, children }) { return <label className="cms-field"><span>{label} <span className="req">*</span></span><select value={value} disabled={disabled} onChange={(event) => onChange(event.target.value)}><option value="">Select {label}</option>{children}</select></label>; }
function Summary({ label, value }) { return <div className="allocation-summary-item"><span>{label}</span><strong>{value ?? "—"}</strong></div>; }
function CardHead({ title, text, icon }) { return <div className="cms-card-head allocation-card-head"><div><h3>{title}</h3><p>{text}</p></div>{icon}</div>; }
function SearchBox({ value, onChange }) { return <div className="allocation-table-tools"><Search size={17} /><input value={value} onChange={(event) => onChange(event.target.value)} placeholder="Search by student name, admission no or roll no..." /></div>; }
function StudentTable({ students, pending = false, onEdit, showAdmissionDate = true, showStatus = true, iconOnlyEdit = false }) { const status = (student) => filled(student.rollNo) ? "Roll Allocated" : filled(student.sectionId) || student.sectionName ? "Section Allocated" : "Unallocated"; const columns = 2 + (showAdmissionDate ? 1 : 0) + (pending ? 0 : 2) + (showStatus ? 1 : 0) + (onEdit ? 1 : 0); return <div className="cms-table-wrap"><table className="cms-table allocation-students-table"><thead><tr><th>Admission No</th><th>Student Name</th>{showAdmissionDate ? <th>Admission Date</th> : null}{!pending ? <><th>Section</th><th>Roll No</th></> : null}{showStatus ? <th>Allocation Status</th> : null}{onEdit ? <th>Action</th> : null}</tr></thead><tbody>{students.length ? students.map((student) => <tr key={student.id ?? student.admissionNo}><td>{student.admissionNo || "—"}</td><td className="cms-font-semibold">{student.name || "—"}</td>{showAdmissionDate ? <td>{date(student.admissionDate)}</td> : null}{!pending ? <><td>{student.sectionName || "—"}</td><td>{student.rollNo || "—"}</td></> : null}{showStatus ? <td><StatusBadge value={status(student)} /></td> : null}{onEdit ? <td><button className={`cms-btn cms-btn-ghost${iconOnlyEdit ? " allocation-edit-icon-button" : ""}`} title="Edit" aria-label="Edit" onClick={() => onEdit(student)}><Pencil size={16} />{!iconOnlyEdit ? "Edit" : null}</button></td> : null}</tr>) : <tr><td colSpan={columns}><div className="cms-empty">No students found for this allocation status.</div></td></tr>}</tbody></table></div>; }
function PreviewCard({ preview, sections, program, totalAvailable, busy, onCancel, onConfirm }) { const rows = list(preview?.students); const capacities = new Map(sections.map((section) => [String(section.id), section])); return <section className="allocation-preview-card"><div className="allocation-preview-head"><div><h3>Preview Section Allocation</h3><p>Review the backend-proposed allocations before confirmation.</p></div><span>Preview Only – Changes are not saved yet</span></div><div className="allocation-summary allocation-preview-summary"><Summary label="Students to Allocate" value={get(preview, "studentsToAllocate", "StudentsToAllocate") ?? rows.length} /><Summary label="Available Sections" value={sections.filter((section) => section.available > 0).length} /><Summary label="Total Capacity" value={get(preview, "totalCapacity", "TotalCapacity") ?? "—"} /><Summary label="Available Capacity" value={totalAvailable} /></div><div className="cms-table-wrap"><table className="cms-table allocation-preview-table"><thead><tr><th>Student Name</th><th>Admission No.</th><th>Program</th><th>Proposed Section</th><th>Section Capacity</th><th>Status</th></tr></thead><tbody>{rows.length ? rows.map((student) => { const section = capacities.get(String(get(student, "sectionId", "SectionId"))); return <tr key={get(student, "studentId", "StudentId")}><td className="cms-font-semibold">{get(student, "studentName", "StudentName") || "—"}</td><td>{get(student, "admissionNo", "AdmissionNo") || "—"}</td><td>{program || "—"}</td><td>{get(student, "sectionName", "SectionName") || "—"}</td><td>{section ? `${section.allocated} / ${section.maximum}` : "—"}</td><td><StatusBadge value="Ready" /></td></tr>; }) : <tr><td colSpan="6"><div className="cms-empty">The preview returned no students to allocate.</div></td></tr>}</tbody></table></div><div className="allocation-preview-footer"><button className="cms-btn cms-btn-ghost" disabled={Boolean(busy)} onClick={onCancel}>Cancel</button><button className="cms-btn cms-btn-primary" disabled={Boolean(busy) || !rows.length} onClick={onConfirm}>Confirm Section Allocation</button></div></section>; }
