-- Database Script to optimize Staff table and create assignment tables

-- 1. Create StaffCampusAssignments
CREATE TABLE IF NOT EXISTS `StaffCampusAssignments` (
    `Id` INT NOT NULL AUTO_INCREMENT,
    `StaffId` INT NOT NULL,
    `CampusId` INT NOT NULL,
    `IsPrimary` TINYINT(1) NOT NULL DEFAULT 0,
    `AssignedDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
    `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UpdatedAt` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`Id`),
    INDEX `IX_StaffCampus_StaffId` (`StaffId`),
    INDEX `IX_StaffCampus_CampusId` (`CampusId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. Create StaffBoardAssignments
CREATE TABLE IF NOT EXISTS `StaffBoardAssignments` (
    `Id` INT NOT NULL AUTO_INCREMENT,
    `StaffId` INT NOT NULL,
    `BoardId` INT NOT NULL,
    `IsPrimary` TINYINT(1) NOT NULL DEFAULT 0,
    `AssignedDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
    `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UpdatedAt` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`Id`),
    INDEX `IX_StaffBoard_StaffId` (`StaffId`),
    INDEX `IX_StaffBoard_BoardId` (`BoardId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. Add necessary columns to Staff table safely
DROP PROCEDURE IF EXISTS `OptimizeStaffTable`;
DELIMITER //
CREATE PROCEDURE `OptimizeStaffTable`()
BEGIN
    -- Add Driving fields if missing
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Staff' AND COLUMN_NAME = 'IsDriver') THEN
        ALTER TABLE `Staff` ADD `IsDriver` TINYINT(1) NOT NULL DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Staff' AND COLUMN_NAME = 'DrivingLicenseNumber') THEN
        ALTER TABLE `Staff` ADD `DrivingLicenseNumber` VARCHAR(100) NULL;
    END IF;
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Staff' AND COLUMN_NAME = 'DrivingLicenseExpiryDate') THEN
        ALTER TABLE `Staff` ADD `DrivingLicenseExpiryDate` DATE NULL;
    END IF;
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Staff' AND COLUMN_NAME = 'DrivingExperienceYears') THEN
        ALTER TABLE `Staff` ADD `DrivingExperienceYears` INT NULL;
    END IF;
    
    -- Ensure JSON columns exist instead of separate tables to avoid clumsiness
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Staff' AND COLUMN_NAME = 'DepartmentSpecificJson') THEN
        ALTER TABLE `Staff` ADD `DepartmentSpecificJson` LONGTEXT NULL;
    END IF;
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Staff' AND COLUMN_NAME = 'EducationJson') THEN
        ALTER TABLE `Staff` ADD `EducationJson` LONGTEXT NULL;
    END IF;
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Staff' AND COLUMN_NAME = 'ExperienceJson') THEN
        ALTER TABLE `Staff` ADD `ExperienceJson` LONGTEXT NULL;
    END IF;
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Staff' AND COLUMN_NAME = 'DocumentsJson') THEN
        ALTER TABLE `Staff` ADD `DocumentsJson` LONGTEXT NULL;
    END IF;
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Staff' AND COLUMN_NAME = 'BankDetailsJson') THEN
        ALTER TABLE `Staff` ADD `BankDetailsJson` LONGTEXT NULL;
    END IF;
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Staff' AND COLUMN_NAME = 'EmergencyContactJson') THEN
        ALTER TABLE `Staff` ADD `EmergencyContactJson` LONGTEXT NULL;
    END IF;

    -- Add missing Profile Lifecycle Workflow Fields if not exists
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Staff' AND COLUMN_NAME = 'ProfileStatus') THEN
        ALTER TABLE `Staff` ADD `ProfileStatus` VARCHAR(50) NOT NULL DEFAULT 'PendingLink';
    END IF;
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Staff' AND COLUMN_NAME = 'ProfileCompletionPercentage') THEN
        ALTER TABLE `Staff` ADD `ProfileCompletionPercentage` INT NOT NULL DEFAULT 30;
    END IF;
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Staff' AND COLUMN_NAME = 'ProfileLinkToken') THEN
        ALTER TABLE `Staff` ADD `ProfileLinkToken` VARCHAR(100) NULL;
    END IF;
END //
DELIMITER ;

CALL `OptimizeStaffTable`();
