import { useState } from "react";
import { Link } from "react-router-dom";
import StudentCard from "../components/StudentCard.jsx";
import StudentPageHeader from "../components/StudentPageHeader.jsx";
import { fees, student } from "../data/studentMockData.js";

const managed = [["Student ID", student.studentId], ["Admission Number", student.admissionNo], ["Admission Date", student.admissionDate], ["Admission Type", student.admissionType], ["Admission Quota", student.admissionQuota], ["Board", student.board], ["Academic Year", student.academicYear], ["Academic Level", student.academicLevel], ["Group", student.group], ["Programme", student.programme], ["Medium", student.medium], ["Second Language", student.secondLanguage], ["Section", student.section], ["Roll Number", student.rollNo], ["Student Status", student.status]];
const initialFields = { firstName: student.firstName, lastName: student.lastName, gender: student.gender, dateOfBirth: student.dateOfBirth, bloodGroup: student.bloodGroup, aadhaar: student.aadhaar, mobile: student.mobile, email: student.email, religion: student.religion, caste: student.caste, ...student.address, ...student.parents, previousSchoolName: student.previousSchool.name, previousBoard: student.previousSchool.board, passingYear: student.previousSchool.passingYear, previousMarks: student.previousSchool.marks, hallTicket: student.previousSchool.hallTicket };
const labels = { firstName: "First Name", lastName: "Last Name", gender: "Gender", dateOfBirth: "Date of Birth", bloodGroup: "Blood Group", aadhaar: "Aadhaar Number", mobile: "Student Mobile", email: "Email", religion: "Religion", caste: "Caste Category", house: "House / Door Number", street: "Street / Village", town: "Town", district: "District", state: "State", pincode: "Pincode", fatherName: "Father Name", fatherOccupation: "Father Occupation", fatherMobile: "Father Mobile", motherName: "Mother Name", motherOccupation: "Mother Occupation", motherMobile: "Mother Mobile", guardianName: "Guardian Name", guardianMobile: "Guardian Mobile", annualIncome: "Annual Income", previousSchoolName: "Previous School Name", previousBoard: "Previous Board", passingYear: "Year of Passing", previousMarks: "Marks / GPA", hallTicket: "Hall Ticket Number" };
const groups = [["Personal Details", ["firstName", "lastName", "gender", "dateOfBirth", "bloodGroup", "aadhaar", "mobile", "email", "religion", "caste"]], ["Contact & Address", ["house", "street", "town", "district", "state", "pincode"]], ["Parent / Guardian", ["fatherName", "fatherOccupation", "fatherMobile", "motherName", "motherOccupation", "motherMobile", "guardianName", "guardianMobile", "annualIncome"]], ["Previous School", ["previousSchoolName", "previousBoard", "passingYear", "previousMarks", "hallTicket"]]];

export default function StudentProfile() {
  const [values, setValues] = useState(initialFields), [draft, setDraft] = useState(initialFields), [editing, setEditing] = useState(false);
  const save = () => { setValues(draft); setEditing(false); };
  return <div className="sp-page"><StudentPageHeader title="My Profile" subtitle="Review your college-managed information and update personal details." action={!editing ? <button className="sp-btn primary" onClick={() => setEditing(true)}>Edit Personal Details</button> : <div className="sp-actions"><button className="sp-btn" onClick={() => { setDraft(values); setEditing(false); }}>Cancel</button><button className="sp-btn primary" onClick={save}>Save</button></div>}/><section className="sp-profile-hero"><span className="sp-avatar is-xl">{student.initials}</span><div><h2>{values.firstName} {values.lastName}</h2><p>{student.studentId} · Roll No {student.rollNo} · {student.section}</p></div></section>{groups.map(([title, fields]) => <StudentCard key={title} title={title} subtitle={editing ? "You can update these details." : "Student-editable information"}><div className="sp-form-grid">{fields.map((key) => <label key={key}><span>{labels[key]}</span><input value={(editing ? draft : values)[key]} disabled={!editing} onChange={(event) => setDraft((current) => ({ ...current, [key]: event.target.value }))}/></label>)}</div></StudentCard>)}<StudentCard title="College-Managed Academic Information" subtitle="Contact the college office if a correction is required."><div className="sp-detail-grid">{managed.map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></StudentCard><div className="sp-grid-2"><StudentCard title="Student Type & Facility" subtitle="Read only"><div className="sp-detail-grid cols-2">{[["Student Type", student.studentType], ["Transport Required", student.transportRequired], ["Route", "Vijayawada Central"], ["Pickup Point", "Benz Circle"]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></StudentCard><StudentCard title="Fee Summary" subtitle="Read only"><div className="sp-fee-overview"><div><span>Total</span><strong>₹{fees.total.toLocaleString("en-IN")}</strong></div><div><span>Paid</span><strong>₹{fees.paid.toLocaleString("en-IN")}</strong></div><div><span>Due</span><strong>₹{fees.due.toLocaleString("en-IN")}</strong></div></div><p className="sp-muted">Payment Plan: {fees.paymentPlan}</p><Link className="sp-text-link" to="/student-dashboard/fees">View Fee Details →</Link></StudentCard></div></div>;
}
